create database EcommerceProject

Use EcommerceProject;

SELECT TABLE_NAME  
FROM ECommerceProject.INFORMATION_SCHEMA.TABLES;

--preview of the dataset
SELECT TOP 10 * FROM [Orders];

--To Pull Specific Columns
SELECT OrderID,Product,Quantity,TotalPrice
FROM Orders

--WHERE Filter for OrderStatus
SELECT OrderID,Product,OrderStatus,TotalPrice
FROM Orders
WHERE OrderStatus = 'Cancelled'

--Total price of each products in descending order
SELECT OrderID,Product,TotalPrice
FROM Orders
ORDER BY TotalPrice DESC;


-- Average total price per product
SELECT Product, 
    AVG(TotalPrice) AS AverageTotalPrice
FROM Orders
GROUP BY Product
ORDER BY AverageTotalPrice DESC


--Total revenue generated by products in descending order
SELECT Product, 
  SUM(TotalPrice) AS TotalRevenue
FROM Orders
GROUP BY Product
ORDER BY TotalRevenue DESC;

--Number of Orders Generated by each order status
SELECT OrderStatus, 
  COUNT(*) AS NumberOfOrders
FROM Orders
GROUP BY OrderStatus
ORDER BY NumberOfOrders DESC;

--Average Total Price by Payment Method
SELECT PaymentMethod,
  AVG(TotalPrice) AS AverageOrderValue
FROM Orders
GROUP BY PaymentMethod
ORDER BY AverageOrderValue DESC;

--Revenue from Cancelled Orders by Products
SELECT Product,
  SUM(TotalPrice) AS RevenueFromCancelledOrders
FROM Orders
WHERE OrderStatus = 'Cancelled'
GROUP BY Product
ORDER BY RevenueFromCancelledOrders DESC;
